### PR TITLE
added a score functionality

### PR DESCRIPTION
**Pull request by vivian-dai**
Here's an example of it working

image

### CODE REVIEW

**Comment by Jayt257** [comment]
Can you do one thing more about that opponenet score text? Try to put that text inside a button or a box so that it is visible in background.

**Comment by vivian-dai** [comment]
Just opponent text or do you want both scores to be in a box?

**Comment by Jayt257** [comment]
both scores in the box.

**Comment by vivian-dai** [comment]
Here is how it looks now:
image

**Pull request merged**
